### PR TITLE
fix(shadow-to-light): correctly transform imported .css

### LINKED ISSUE #25: ENOENT: no such file or directory for CSS file when HTML file is imported into JS
If you do `import template from './component.html'` and there is also a `component.css` file in the same directory, then you'll get an error:

```
ENOENT: no such file or directory, lstat '/.../x/component/component.css'
```

The issue seems to be that we are mixing up relative file paths with absolute file paths, and so we end up trying to delete the same underlying file twice.

Repro: f0aae58

### PR DESCRIPTION
**Pull request by nolanlawson**
This fixes #25 (error when trying to delete the same `.css` file more than once) as well as fixing an additional issue, which is that `shadow-to-light` was not properly transforming:

```js
import sheet from './sheet.css'
```

to

```js
import sheet from './sheet.scoped.css'
```

There is an additional issue where we don't handle `import stylesheet from './notReferencedByTemplate.css'` but I'll open a separate issue for that.

### CODE REVIEW

File: bin/smoke-test.sh [hunk 1]
```diff
@@ -11,7 +11,12 @@ for TRANSFORM in $(ls ./tests/fixtures); do
     mkdir -p "/tmp/lwc-codemod-tests/${TRANSFORM}"
     cp -R "./tests/fixtures/${TRANSFORM}/${DIR}" "/tmp/lwc-codemod-tests/${TRANSFORM}/${DIR}"
 
-    node ./transforms/cli.js "${TRANSFORM}" "/tmp/lwc-codemod-tests/${TRANSFORM}/${DIR}"
+    CLI_PATH="$(pwd)/transforms/cli.js"
+
+    # intentionally test with a relative file path since that's what most users will do
+    cd /tmp/lwc-codemod-tests
+    node "$CLI_PATH" "${TRANSFORM}" "${TRANSFORM}/${DIR}"
+    cd -
```
Comment (nolanlawson) [inline bin/smoke-test.sh:19]: This is not strictly necessary for the repro, but I feel like it's a good safety measure. Most users will do `npx lwc-codemod <mod> ./path/to/something` rather than provide a full absolute path.

**Review by divmain — APPROVED** [review]
